import {
  Activity,
  Angry,
  Anvil,
  Axe,
  Backpack,
  BookOpenText,
  Brain,
  ChefHat,
  CircleDot,
  Crosshair,
  Crown,
  Eye,
  Fish,
  Flame,
  FlaskConical,
  Footprints,
  GlassWater,
  Hand,
  HandCoinsIcon,
  HandFist,
  Heart,
  Layers,
  Leaf,
  Pickaxe,
  Rabbit,
  Scroll,
  Shield,
  ShieldHalf,
  Skull,
  Sparkles,
  Speech,
  Sword,
  Swords,
  Tent,
  TreePine,
  Wind,
  Zap,
} from "lucide-react"
import { JSX } from "react"
import {
  GiBelt,
  GiBigDiamondRing,
  GiCardboardBoxClosed,
  GiChestArmor,
  GiCrafting,
  GiCrestedHelmet,
  GiCrystalBall,
  GiDropWeapon,
  GiEmeraldNecklace,
  GiEyeTarget,
  GiFootsteps,
  GiHighGrass,
  GiMushroomGills,
  GiSteeltoeBoots,
  GiStoneAxe,
  GiStoneBlock,
  GiWoodPile,
} from "react-icons/gi"
import styles from "./icons.module.css"

const iconMap: Record<string, JSX.Element> = {
  // Stats
  GiMushroomGills: <GiMushroomGills className={styles.brown} />,
  GiHighGrass: <GiHighGrass className={styles.green} />,
  GiStoneBlock: <GiStoneBlock className={styles.gray} />,
  Heart: <Heart className={styles.red} />,
  Zap: <Zap className={styles.yellow} />,
  Shield: <Shield className={styles.blue} />,
  Sword: <Sword className={styles.gray} />,
  Flame: <Flame className={styles.orange} />,
  HandFist: <HandFist className={styles.brown} />,
  Activity: <Activity className={styles.orange} />,
  Skull: <Skull className={styles.purple} />,
  Rabbit: <Rabbit className={styles.green} />,
  BookOpenText: <BookOpenText className={styles.orange} />,
  Brain: <Brain className={styles.purple} />,
  Speech: <Speech className={styles.blue} />,
  TreePine: <TreePine className={styles.green} />,
  Tent: <Tent className={styles.brown} />,
  HandCoinsIcon: <HandCoinsIcon className={styles.gold} />,
  Eye: <Eye className={styles.gold} />,
  // Weapon skills
  SwordMastery: <Sword className={styles.gray} />,
  HeavySword: <Sword className={styles.gray} />,
  DualSword: <Swords className={styles.gray} />,
  Axe: <Axe className={styles.brown} />,
  Archery: <Crosshair className={styles.green} />,
  // Defense skills
  HeavyShield: <ShieldHalf className={styles.blue} />,
  // Other skills
  Tactics: <Scroll className={styles.gold} />,
  Endurance: <Heart className={styles.red} />,
  Leadership: <Crown className={styles.gold} />,
  Intellect: <Brain className={styles.purple} />,
  Stealth: <Wind className={styles.cyan} />,
  Magic: <Sparkles className={styles.purple} />,
  // Crafting skills
  Alchemy: <FlaskConical className={styles.green} />,
  Blacksmithing: <Anvil className={styles.brown} />,
  Anvil: <Anvil className={styles.brown} />,
  Cooking: <ChefHat className={styles.orange} />,
  Fishing: <Fish className={styles.blue} />,
  Mining: <Pickaxe className={styles.gray} />,
  Pickaxe: <Pickaxe className={styles.gray} />,
  Herbalism: <Leaf className={styles.green} />,
  // Gear slots
  Armour: <Layers className={styles.blue} />,
  Belt: <Backpack className={styles.brown} />,
  Boots: <Footprints className={styles.brown} />,
  Gloves: <Hand className={styles.brown} />,
  Cloak: <Wind className={styles.gray} />,
  Ring: <CircleDot className={styles.gold} />,
  Necklace: <GlassWater className={styles.blue} />,
  Angry: <Angry className={styles.black} />,
  GiCrestedHelmet: <GiCrestedHelmet className={styles.gray} />,
  GiEmeraldNecklace: <GiEmeraldNecklace className={styles.green} />,
  GiChestArmor: <GiChestArmor className={styles.red} />,
  GiBigDiamondRing: <GiBigDiamondRing className={styles.gold} />,
  GiBelt: <GiBelt className={styles.brown} />,
  GiSteeltoeBoots: <GiSteeltoeBoots className={styles.brown} />,
  GiDropWeapon: <GiDropWeapon className={styles.gray} />,
  GiEyeTarget: <GiEyeTarget className={styles.gold} />,
  GiCrystalBall: <GiCrystalBall className={styles.gold} />,
  GiCrafting: <GiCrafting className={styles.gray} />,
  GiFootsteps: <GiFootsteps className={styles.brown} />,
  GiStoneAxe: <GiStoneAxe className={styles.silver} />,
  GiWoodPile: <GiWoodPile className={styles.brown} />,
  default: <GiCardboardBoxClosed className={styles.brown} />,
}

export default function getIcon(iconKey?: string) {
  if (!iconKey) return null
  return iconMap[iconKey] ?? null
}
