world.get_player_position
world.get_player_vision_players_positions

-- to chyba nie bo zawsze bedzie wszystko widoczne na mapie ?
world.get_player_vision_on_tile
world.get_player_vision_cities
world.get_player_vision_districts

players.get_player_knowledge_on_player
buildings.get_player_knowledge_on_building
cities.get_player_knowledge_on_city
districts.get_player_knowledge_on_district
world.get_player_knowledge_on_map_tile
inventory.get_player_knowledge_on_inventory