-- players.player_abilities definition

-- Drop table

 DROP TABLE players.player_abilities;

CREATE TABLE attributes.player_abilities (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	player_id int4 NOT NULL,
	ability_id int4 NOT NULL,
	value int4 NOT NULL,
	CONSTRAINT player_abilities_pkey PRIMARY KEY (id)
);



-- players.player_skills definition

-- Drop table

 DROP TABLE players.player_skills;

CREATE TABLE attributes.player_skills (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	player_id int4 NOT NULL,
	skill_id int4 NOT NULL,
	value int4 NOT NULL,
	CONSTRAINT player_skills_pkey PRIMARY KEY (id)
);


-- players.player_skills foreign keys

ALTER TABLE attributes.player_skills ADD CONSTRAINT player_skills_skills_fk FOREIGN KEY (skill_id) REFERENCES "attributes".skills(id);



-- players.player_stats definition

-- Drop table

 DROP TABLE players.player_stats;

CREATE TABLE attributes.player_stats (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	player_id int4 NOT NULL,
	stat_id int4 NOT NULL,
	value int4 NOT NULL,
	CONSTRAINT player_stats_pkey PRIMARY KEY (id)
);





ALTER TABLE "attributes".player_stats ADD CONSTRAINT player_stats_players_fk FOREIGN KEY (player_id) REFERENCES players.players(id);
ALTER TABLE "attributes".player_stats ADD CONSTRAINT player_stats_stats_fk FOREIGN KEY (stat_id) REFERENCES "attributes".stats(id);



ALTER TABLE "attributes".player_skills ADD CONSTRAINT player_skills_players_fk FOREIGN KEY (player_id) REFERENCES players.players(id);
ALTER TABLE "attributes".player_skills ADD CONSTRAINT player_skills_skills_fk FOREIGN KEY (skill_id) REFERENCES "attributes".skills(id);



ALTER TABLE "attributes".player_abilities ADD CONSTRAINT player_abilities_abilities_fk FOREIGN KEY (ability_id) REFERENCES "attributes".abilities(id);
ALTER TABLE "attributes".player_abilities ADD CONSTRAINT player_abilities_players_fk FOREIGN KEY (player_id) REFERENCES players.players(id);

