-- inventory.inventory_slots definition

-- Drop table

 DROP TABLE inventory.inventory_slots;

CREATE TABLE inventory.inventory_slots (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	inventory_container_id int4 NOT NULL,
	item_id int4 NULL,
	quantity int4 NULL,
	CONSTRAINT inventory_slots_pkey PRIMARY KEY (id),
	CONSTRAINT inventory_slots_quantity_check CHECK ((quantity >= 0))
);


-- inventory.inventory_slots foreign keys

ALTER TABLE inventory.inventory_slots ADD CONSTRAINT inventory_slots_inventory_container_id_fkey FOREIGN KEY (inventory_container_id) REFERENCES inventory.inventory_containers(id) ON DELETE CASCADE;
ALTER TABLE inventory.inventory_slots ADD CONSTRAINT inventory_slots_items_fk FOREIGN KEY (item_id) REFERENCES items.items(id);